-- AlterTable
ALTER TABLE "ExerciseVideo" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "sets" DROP NOT NULL,
ALTER COLUMN "reps" DROP NOT NULL;

-- AlterTable
ALTER TABLE "MechanicsGuide" ADD COLUMN     "phase" TEXT NOT NULL DEFAULT '전체',
ADD COLUMN     "sortOrder" INTEGER NOT NULL DEFAULT 0;
